# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Bault

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_19cdd4cafad1489586397d8c20eb2030 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_be30078e609e426488ddafe3fb621f53 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_19cdd4cafad1489586397d8c20eb2030 }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Bault'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_102f46c043664c2c99e9407a95deec13 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_19cdd4cafad1489586397d8c20eb2030 }}/appsvc/wordpress-alpine-php:${{ github.sha }}'